### ISSUE TITLE
Upload error (500) with version 2.0

### ISSUE THREAD

**Issue by Dave247** [poma/Hotsapi.Uploader#37]
Having just updated the uploader wanting to upload a backlog of replays, I noticed it taking much longer then usual then throwing up errors. Looking at the logs and seeing a lot of 500 errors I don't know if it's do do with the program, or if there's an issue with the server.

```
[2017-12-11 00:21:27.2788] INFO: App v2.0 started 
[2017-12-11 00:21:27.6946] DEBUG: Started watching for new replays 
[2017-12-11 00:22:19.8027] WARN: Error checking fingerprint '3b0c3a5b-9d67-3576-0396-a5f1e9ecca0c' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<CheckDuplicate>d__9.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 92
[2017-12-11 00:22:21.0681] WARN: Error checking fingerprint 'e3b50f20-24eb-de15-e8d1-cb5010fc9f07' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<CheckDuplicate>d__9.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 92
[2017-12-11 00:23:10.4001] WARN: Error checking fingerprint 'd6146743-1c97-bca5-1a91-ad257287ec75' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<CheckDuplicate>d__9.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 92
[2017-12-11 00:23:12.4004] WARN: Error checking fingerprint 'cd10f937-d1e1-2534-b21c-0a6c4c869ede' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<CheckDuplicate>d__9.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 92
[2017-12-11 00:24:07.8941] WARN: Error uploading file 'C:\Users\david\OneDrive\Dave-i7\Documents\Heroes of the Storm\Accounts\57176541\1-Hero-1-449753\Replays\Multiplayer\Braxis Holdout (34).StormReplay' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<Upload>d__8.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 57
[2017-12-11 00:24:10.1844] WARN: Error uploading file 'C:\Users\david\OneDrive\Dave-i7\Documents\Heroes of the Storm\Accounts\57176541\1-Hero-1-449753\Replays\Multiplayer\Cursed Hollow (58).StormReplay' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<Upload>d__8.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 57
[2017-12-11 00:25:08.0942] WARN: Error uploading file 'C:\Users\david\OneDrive\Dave-i7\Documents\Heroes of the Storm\Accounts\57176541\1-Hero-1-449753\Replays\Multiplayer\Infernal Shrines (34).StormReplay' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<Upload>d__8.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 57
[2017-12-11 00:25:11.1917] WARN: Error uploading file 'C:\Users\david\OneDrive\Dave-i7\Documents\Heroes of the Storm\Accounts\57176541\1-Hero-1-449753\Replays\Multiplayer\Battlefield of Eternity (45).StormReplay' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<Upload>d__8.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 57
[2017-12-11 00:25:59.9112] WARN: Error checking fingerprint '8fdb3ecd-025c-ee74-6669-a376f16d2936' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<CheckDuplicate>d__9.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 92
[2017-12-11 00:26:03.0417] WARN: Error checking fingerprint '2f6bb576-4f2c-b2ce-b062-50b6aca05260' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<CheckDuplicate>d__9.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 92
[2017-12-11 00:26:51.9868] WARN: Error checking fingerprint '4ccc4695-464d-b5bd-4320-3a3f23ab022e' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<CheckDuplicate>d__9.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 92
[2017-12-11 00:26:54.3605] WARN: Error checking fingerprint '1db089a1-1232-d9ba-663a-f207add1dc63' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<CheckDuplicate>d__9.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 92
[2017-12-11 00:27:52.1992] WARN: Error uploading file 'C:\Users\david\OneDrive\Dave-i7\Documents\Heroes of the Storm\Accounts\57176541\1-Hero-1-449753\Replays\Multiplayer\Infernal Shrines (33).StormReplay' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<Upload>d__8.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 57
[2017-12-11 00:27:57.2595] WARN: Error uploading file 'C:\Users\david\OneDrive\Dave-i7\Documents\Heroes of the Storm\Accounts\57176541\1-Hero-1-449753\Replays\Multiplayer\Volskaya Foundry (6).StormReplay' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<Upload>d__8.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 57
[2017-12-11 00:28:49.1274] WARN: Error uploading file 'C:\Users\david\OneDrive\Dave-i7\Documents\Heroes of the Storm\Accounts\57176541\1-Hero-1-449753\Replays\Multiplayer\Dragon Shire (48).StormReplay' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<Upload>d__8.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 57
[2017-12-11 00:28:59.1514] WARN: Error uploading file 'C:\Users\david\OneDrive\Dave-i7\Documents\Heroes of the Storm\Accounts\57176541\1-Hero-1-449753\Replays\Multiplayer\Sky Temple (47).StormReplay' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<Upload>d__8.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 57
[2017-12-11 00:29:40.7393] WARN: Error checking fingerprint 'cbb145cf-e20e-3874-b10a-c213087f87b9' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<CheckDuplicate>d__9.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 92
[2017-12-11 00:29:50.2191] WARN: Error checking fingerprint '05b51d66-cb28-d767-d394-e198772d1406' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<CheckDuplicate>d__9.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 92
[2017-12-11 00:30:42.0043] WARN: Error uploading file 'C:\Users\david\OneDrive\Dave-i7\Documents\Heroes of the Storm\Accounts\57176541\1-Hero-1-449753\Replays\Multiplayer\Cursed Hollow (57).StormReplay' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<Upload>d__8.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 57
[2017-12-11 00:30:50.2467] WARN: Error uploading file 'C:\Users\david\OneDrive\Dave-i7\Documents\Heroes of the Storm\Accounts\57176541\1-Hero-1-449753\Replays\Multiplayer\Braxis Holdout (33).StormReplay' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<Upload>d__8.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 57
```

**Comment by NindroidX** [comment]
I'm having the same problem after updating the 1.2 client to 2.0. Uninstalling + reinstalling does not fix it for me either.

**Comment by Dave247** [comment]
Using the unintended method to downgrade the program to a previous version as outlined in #30 doesn't change the outcome, so I'm going to conclude that there is something wrong with the server.

**Comment by poma** [comment]
Sorry I was away from my computer for 3 days but it should be fixed now. This is due to a job processing bug in Laravel, I really should migrate job queue to Redis but I don't have a stable server for it yet.
