### ISSUE TITLE
Failure to upload replays: (500) Internal Server Error

### ISSUE THREAD

**Issue by herrvigg** [poma/Hotsapi.Uploader#39]
Since yesterday the replays can't be uploaded anymore, due to an error on the server. Here are the logs:

```
[2018-01-06 21:56:13.2641] WARN: Error uploading file 'C:\Users\xxx\Documents\Heroes of the Storm\Accounts\113048474\2-Hero-1-3443385\Replays\Multiplayer\Braxis Holdout (10).StormReplay' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<Upload>d__8.MoveNext() in C:\projects\hotsapi-uploader\Hotsapi.Uploader.Common\Uploader.cs:line 57
```

**Comment by Shanadar** [comment]
Exact same problem experienced here as well.

**Comment by rcjsuen** [comment]
The web UI also doesn't work. :(

**Comment by rcjsuen** [comment]
I can upload from the web UI again.

**Comment by herrvigg** [comment]
Yes it works again :)

**Comment by poma** [comment]
I forgot to enable log rotation so it grew and consumed all disk space
