### ISSUE TITLE
Upload errors after new Hots update

### ISSUE THREAD

**Issue by daddz** [poma/Hotsapi.Uploader#42]
The uploader started to have failures on (I guess) new replays:
```
[2018-04-13 21:03:50.1066] INFO: App v2.0.1 started 
[2018-04-13 21:03:50.5974] DEBUG: Started watching for new replays 
[2018-04-13 21:03:50.7891] WARN: Error analyzing file E:\foobar\Documents\Heroes of the Storm\Accounts\123457890\2-Hero-1-1234567\Replays\Multiplayer\Tomb of the Spider Queen (323).StormReplay System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Heroes.ReplayParser.ReplayInitData.Parse(Replay replay, Byte[] buffer)
   at Heroes.ReplayParser.DataParser.ParseReplayArchive(Replay replay, MpqArchive archive, Boolean ignoreErrors, Boolean skipEventParsing, Boolean skipUnitParsing, Boolean skipMouseMoveEvents)
   at Heroes.ReplayParser.DataParser.ParseReplay(String fileName, Boolean ignoreErrors, Boolean deleteFile, Boolean allowPTRRegion, Boolean skipEventParsing, Boolean skipUnitParsing, Boolean skipMouseMoveEvents)
   at Hotsapi.Uploader.Common.Analyzer.Analyze(ReplayFile file)
[2018-04-13 21:03:50.7891] WARN: Error analyzing file E:\foobar\Documents\Heroes of the Storm\Accounts\123457890\2-Hero-1-1234567\Replays\Multiplayer\Braxis Holdout (275).StormReplay System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Heroes.ReplayParser.ReplayInitData.Parse(Replay replay, Byte[] buffer)
   at Heroes.ReplayParser.DataParser.ParseReplayArchive(Replay replay, MpqArchive archive, Boolean ignoreErrors, Boolean skipEventParsing, Boolean skipUnitParsing, Boolean skipMouseMoveEvents)
   at Heroes.ReplayParser.DataParser.ParseReplay(String fileName, Boolean ignoreErrors, Boolean deleteFile, Boolean allowPTRRegion, Boolean skipEventParsing, Boolean skipUnitParsing, Boolean skipMouseMoveEvents)
   at Hotsapi.Uploader.Common.Analyzer.Analyze(ReplayFile file)
[2018-04-13 21:03:50.7921] WARN: Error analyzing file E:\foobar\Documents\Heroes of the Storm\Accounts\123457890\2-Hero-1-1234567\Replays\Multiplayer\Cursed Hollow (334).StormReplay System.NullReferenceException: Object reference not set to an instance of an object.
   at Heroes.ReplayParser.ReplayInitData.Parse(Replay replay, Byte[] buffer)
   at Heroes.ReplayParser.DataParser.ParseReplayArchive(Replay replay, MpqArchive archive, Boolean ignoreErrors, Boolean skipEventParsing, Boolean skipUnitParsing, Boolean skipMouseMoveEvents)
   at Heroes.ReplayParser.DataParser.ParseReplay(String fileName, Boolean ignoreErrors, Boolean deleteFile, Boolean allowPTRRegion, Boolean skipEventParsing, Boolean skipUnitParsing, Boolean skipMouseMoveEvents)
   at Hotsapi.Uploader.Common.Analyzer.Analyze(ReplayFile file)
[2018-04-13 21:03:50.7921] WARN: Error analyzing file E:\foobar\Documents\Heroes of the Storm\Accounts\123457890\2-Hero-1-1234567\Replays\Multiplayer\Tomb of the Spider Queen (322).StormReplay System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Heroes.ReplayParser.ReplayInitData.Parse(Replay replay, Byte[] buffer)
   at Heroes.ReplayParser.DataParser.ParseReplayArchive(Replay replay, MpqArchive archive, Boolean ignoreErrors, Boolean skipEventParsing, Boolean skipUnitParsing, Boolean skipMouseMoveEvents)
   at Heroes.ReplayParser.DataParser.ParseReplay(String fileName, Boolean ignoreErrors, Boolean deleteFile, Boolean allowPTRRegion, Boolean skipEventParsing, Boolean skipUnitParsing, Boolean skipMouseMoveEvents)
   at Hotsapi.Uploader.Common.Analyzer.Analyze(ReplayFile file)
[2018-04-13 21:03:53.8563] DEBUG: Uploaded file 'E:\foobar\Documents\Heroes of the Storm\Accounts\123457890\2-Hero-1-1234567\Replays\Multiplayer\Braxis Holdout (275).StormReplay': UploadError 
[2018-04-13 21:03:55.2864] DEBUG: Uploaded file 'E:\foobar\Documents\Heroes of the Storm\Accounts\123457890\2-Hero-1-1234567\Replays\Multiplayer\Tomb of the Spider Queen (323).StormReplay': UploadError 
[2018-04-13 21:03:56.7162] DEBUG: Uploaded file 'E:\foobar\Documents\Heroes of the Storm\Accounts\123457890\2-Hero-1-1234567\Replays\Multiplayer\Cursed Hollow (334).StormReplay': UploadError 
[2018-04-13 21:04:00.6487] DEBUG: Uploaded file 'E:\foobar\Documents\Heroes of the Storm\Accounts\123457890\2-Hero-1-1234567\Replays\Multiplayer\Tomb of the Spider Queen (322).StormReplay': UploadError 
[2018-04-13 21:04:01.0301] DEBUG: Uploaded file 'E:\foobar\Documents\Heroes of the Storm\Accounts\123457890\2-Hero-1-1234567\Replays\Multiplayer\Tomb of the Spider Queen (321).StormReplay': UploadError 
```

**Comment by daddz** [comment]
It's working again
